name: Generate Snake

# Trigger the action every day at midnight
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Generate the snake contribution graph
      - name: Generate snake graph
        uses: Platane/snk@master
        with:
          github_user_name: PatheticUser  # Replace with your GitHub username

      # Step 3: Commit and push the updated snake graph
      - name: Commit snake graph
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Updated snake contribution graph"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
